### ISSUE TITLE
Use checkLocationServicesIsEnabled to check location service without show popup

### ISSUE THREAD

**Issue by pewh** [webyonet/react-native-android-location-services-dialog-box#12]
What I need is show returned value if current location is enabled or not without show popup. Thanks

**Comment by webyonet** [comment]
This plugin only popup show if location service is turned off.

**Comment by privateOmega** [comment]
@webyonet  I think it does show even if location is enabled :/

**Comment by webyonet** [comment]
@privateOmega
Simulator may have this problem. Would you test it on a real device?

**Comment by privateOmega** [comment]
@webyonet I am using it on a real device. Android 7.1.1. Can you please confirm and modify it?
