### ISSUE TITLE
get error when location is on

### ISSUE THREAD

**Issue by northern-fox** [webyonet/react-native-android-location-services-dialog-box#17]
Looks like the app doesn't have the permission to access location. Add the following line to your app's AndroidManifest.xml:
<uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>

**Comment by Suresh-R-S** [comment]
I'am getting this too. I've set the permission in AndroidManifest.xml. 
But when we see the permissions of the app, location is not seen. 
I'am testing it in a real device.

**Comment by webyonet** [comment]
I will solve this bug on the weekend

**Comment by webyonet** [comment]
This bug tested with RN-45 on android 6 tablet and android 7 mobile phone.
No problems found.
Please check your own code or upgrade to RN latest version.

<img src="https://user-images.githubusercontent.com/973302/27251831-80051c9c-5358-11e7-9566-738ed68719a6.JPG" width="600"/>

**Comment by webyonet** [comment]
```
 LocationServicesDialogBox.checkLocationServicesIsEnabled({
            message: "Use Location ?",
            ok: "YES",
            cancel: "NO"
        }).then(function(success) {
            navigator.geolocation.getCurrentPosition((position) => {
                let initialPosition = JSON.stringify(position);
                this.setState({ initialPosition });
            }, error => console.log(error), { enableHighAccuracy: false, timeout: 20000, maximumAge: 1000 });
        }.bind(this)).catch(function(error) {
            this.setState({
                initialPosition: error.message
            });
        }.bind(this));
```
