### ISSUE TITLE
app is crashing if installing the app without enabling the GPS

### ISSUE THREAD

**Issue by anjali14garg** [webyonet/react-native-android-location-services-dialog-box#19]
Hello, I have included the plugin in my app and app is crashing if i am installing the app without enabling the location.
Can you please help me out in this issue.
Using this plugin in Android

**Comment by webyonet** [comment]
Can you elaborate more on what errors you get -

1) Code to reproduce
2) Stack Trace
3) RN version
4) Android version

**Comment by anjali14garg** [comment]
Thanks for your response actually I removed the cancel option , because of that it was crashing after adding again the cancel option it worked. You can close this issue and thank you for creating this plugin

**Comment by webyonet** [comment]
thanks
