### ISSUE TITLE
Error in using other modules.

### ISSUE THREAD

**Issue by EmpiteDinesh** [webyonet/react-native-android-location-services-dialog-box#2]
Added this to project and it is working fine but getting this error when using other modules ex react-native-image-picker

The callback checkLocationServicesIsEnabled() exists in module LocationServicesDialogBox, but only one callback may be registered to a function in a native module.

**Comment by webyonet** [comment]
you send the code examples and screenshots of the error?

**Comment by EmpiteDinesh** [comment]
This happens when I select image from image picker. There must be a issue in callback.

![screenshot_2016-10-26-11-34-26](https://cloud.githubusercontent.com/assets/17243474/19715068/6e2c03be-9b70-11e6-8c39-9399cafc7cda.png)

**Comment by webyonet** [comment]
before run location services in the callback in the image picker to wait after you run it, I think the problem will be restored

**Comment by EmpiteDinesh** [comment]
Issue is still there, How can I avoid this error in JS code level.

**Comment by webyonet** [comment]
please send to code sample

**Comment by satishsojitra** [comment]
Hi Webyonet,
I am also facing same issue, whenever code in componentDidMount method call twice we are getting this error. We implemented it in home screen in componentDidMount method there it works fine when I go to other screen and come back this home screen again I am getting same error. How to resolve this?
