### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by SergeyMarynenko** [webyonet/react-native-android-location-services-dialog-box#20]
* What went wrong:
Execution failed for task ':react-native-android-location-services-dialog-box:compileReleaseJavaWithJavac'.
> Could not find tools.jar. Please check that C:\Program Files\Java\jre0_144 contains a valid JDK installation.

**Comment by webyonet** [comment]
This problem is related to your jdk. this problem is solved if you reinstall java

**Comment by webyonet** [comment]
or 
[https://stackoverflow.com/questions/11345193/gradle-does-not-find-tools-jar/28805423](https://stackoverflow.com/questions/11345193/gradle-does-not-find-tools-jar/28805423)
