### ISSUE TITLE
How to know when GPS was enabled?

### ISSUE THREAD

**Issue by denebchorny** [webyonet/react-native-android-location-services-dialog-box#21]
I want to know how to check if the gps was enabled by the user after the displayed dialog or before.

I mean, using you method there could be 2 stages:
```
LocationServicesDialogBox.checkLocationServicesIsEnabled({
            message: "",
            cancel: "",
            ok: ""
        })  
        .then(function (success) {})
        .catch((error) => {  });
```
1) If the GPS is enabled (before showing the dialog) calling your method will return success 
2) If the GPS is disabled (before showing the dialog) calling your method will return succes if and only if the user enable the GPS in the prompted interface

**Why I need this?**
I have a button. If it is pressed and the GPS is disabled I show a dialog, and if the user enable the GPS in the prompted interface I dont want to continue the process instead the user has to click the button again.

In the case the GPS is enabled then there is no any dialog to show.

I don't know if you understand what I'm trying to say.

PD: I don't know if this article could be useful. In my case I don't know how to do what it says 
https://stackoverflow.com/questions/41795968/react-native-check-and-promp-user-to-enable-network-gps/42002015#42002015

How can I achieve this?

**Comment by webyonet** [comment]
At the moment this feature is not supported.
I can add this feature soon. (After and before client interaction)

Thanks.

**Comment by webyonet** [comment]
v2.0.0 fixed

**Comment by Sidibedev** [comment]
I got a error : undefined is not a object (evaluating '_reactNativeAndroidLocationServicesDialogBox2.defauly.checkLocationServicesEnabled')

**Comment by vohoangankhanh** [comment]
TypeError: undefined is not an object (evaluating '_reactNativeAndroidLocationServicesDialogBox2.default.checkLocationServicesIsEnabled') . I have the same error too

**Comment by webyonet** [comment]
RN and android version ?

**Comment by vohoangankhanh** [comment]
yes, react native and running on Android device 6.0

**Comment by stinkymonkeyph** [comment]
had there been any fix for this yet ?

**Comment by arbabi2010** [comment]
TypeError: undefined is not an object (evaluating '_reactNativeAndroidLocationServicesDialogBox2.default.checkLocationServicesIsEnabled') . I have the same error too

I've used this package before in react native 0.46 with version 2.2.1 and work fine but now with react natve 0.51 and this package version 2.5 i get this error

**Comment by webyonet** [comment]
-- restart your PC or MAC (for background process)
-- uninstall your app on mobile device

folow the steps below at the terminal step by step :

```
1) react-native unlink react-native-android-location-services-dialog-box
2) npm uninstall react-native-android-location-services-dialog-box
3) npm install react-native-android-location-services-dialog-box --save
4) react-native link react-native-android-location-services-dialog-box
5) react-native run-android
```

**Comment by webyonet** [comment]
Hi @isaaclem this feature is native for ios

**Comment by arbabi2010** [comment]
I Fix it,
I change compileOnly to Compile and it work properly
