### ISSUE TITLE
Feature Request - Make dialog non-cancelable

### ISSUE THREAD

**Issue by tiaanduplessis** [webyonet/react-native-android-location-services-dialog-box#24]
Thanks for this package. Would it be possible to add a configuration option to make the dialog non-non-cancelable?

**Comment by webyonet** [comment]
Yes it is possible. I can add this feature in the next version

**Comment by webyonet** [comment]
This feature was added to v2.1.0

**Comment by jblancoh** [comment]
Canceling is optional, how do I do it optional?,If I remove this line, the application has an error "couldn't find key cancel in dynamic object"

**Comment by webyonet** [comment]
@jblancoh exception stack trace?
