### ISSUE TITLE
Don't close dialog box if clicked on android back button

### ISSUE THREAD

**Issue by rhenmark** [webyonet/react-native-android-location-services-dialog-box#26]
Thank you for this package. this is great. But, it is possible not to close the dialog box if I click the close back? Could you help me how to implement it?

**Comment by webyonet** [comment]
please update v2.2.0

Then implement the following code:
```
import { BackHandler } from 'react-native';
import LocationServicesDialogBox from "react-native-android-location-services-dialog-box";

componentWillMount(){
   BackHandler.addEventListener('hardwareBackPress', () => {
      LocationServicesDialogBox.forceCloseDialog();
   });  
}
```

**Comment by rhenmark** [comment]
hello sir. the dialog box still closes when I clicked back button. It is possible to add a tag cancelable to false?

**Comment by webyonet** [comment]
I apologize, I understood that I was able to close it.
Write the code below to not close it:
````
BackHandler.addEventListener('hardwareBackPress', () => {
      return false;
});
````

**Comment by rhenmark** [comment]
Thank you. But is it possible to turn on location services without going to the settings?

**Comment by webyonet** [comment]
no. you can use a different module

**Comment by MarinkoIgor** [comment]
Hi there,
I have similar problem, 'return false' does not work for me, also it's not a good solution in my case because I already have on the global level of app main event listener for hardwareBackPress. It's here somehow implemented onBackButtonPress modal prop?
