### ISSUE TITLE
Crash when press the hardware back 

### ISSUE THREAD

**Issue by CliveTeow** [webyonet/react-native-android-location-services-dialog-box#32]
The app will crash scenarios:
1. Click the no button and click hardware back
2. Click hardware back to close the dialog, and click hardware back again.

**Comment by CliveTeow** [comment]
Seems the promise.reject(new Throwable("disabled")); is called twice. (1st time: cancel or first hardware back press, 2nd time: 2nd hardware back press.
Need to add checking in the forceCloseDialog()

**Comment by webyonet** [comment]
RN and android version ?

**Comment by CliveTeow** [comment]
react-native: 0.48.0
Android version: 4.4 (real device)

I only able to test this on real devices. My another real device is XiaoMi Redmi Note 2, which will prompt its own request GPS dialog.

**Comment by Sathiyamm** [comment]
@CliveTeow remove this code and its working correctly in my app.
BackHandler.addEventListener('hardwareBackPress', () => {
   LocationServicesDialogBox.forceCloseDialog();
});
