### ISSUE TITLE
Cannot find symbol Html.FROM_HTML_MODE_LEGACY

### ISSUE THREAD

**Issue by MiceBishop** [webyonet/react-native-android-location-services-dialog-box#35]
According to [this documentation](https://developer.android.com/reference/android/text/Html.html#FROM_HTML_MODE_LEGACY) this attribute has been introduced in api level 24, however the project specifies compileSdkVersion 23 in its build.gradle, thus causing the above error.

Changing the compileSdkVersion to 25 fixes it.

Introduced in 2.4.2 by https://github.com/webyonet/react-native-android-location-services-dialog-box/commit/34b3b7eb7d411d524c390b88b2410bc4774b8b7b.

**Comment by webyonet** [comment]
fix v2.4.2
