### ISSUE TITLE
Error in building

### ISSUE THREAD

**Issue by saigal-prateek** [webyonet/react-native-android-location-services-dialog-box#36]
Hey,
When I am doing react-native run-android, it gives me 3 errors;
1. LocationServicesDialogBoxModule is not abstract and does not override abstract method onActivityResult(int,int, Intent).
2. LocationServicesDialogBoxModule.java:25: error: method does not override or implement a method from a supertype
The third one is same as second one but with different file no
3.  LocationServicesDialogBoxModule.java:125: error: method does not override or implement a method from a supertype

It also gives a note saying that the module LocationServicesDialogBoxModule uses or overrides a deprecated API.

Tried uninstalling/installing this module but of no use.
Tried a clean build but also did not helped.

React-native version is 0.27.2 and cli's 2.0.1

**Comment by webyonet** [comment]
please look here https://github.com/webyonet/react-native-android-location-services-dialog-box/issues/5
