### ISSUE TITLE
app crashed on version 2.2.1

### ISSUE THREAD

**Issue by derakhshanfar** [webyonet/react-native-android-location-services-dialog-box#38]
![untitled](https://user-images.githubusercontent.com/18225394/34512980-fcf22348-f07a-11e7-875a-3b23a7f06600.jpg)

**Comment by webyonet** [comment]
Android and RN version ?

**Comment by derakhshanfar** [comment]
thanks @webyonet , this is my enviroment:
```
OS: Windows 10
Node: 8.9.3
Yarn: 0.27.5
npm: 5.5.1
Watchman: Not Found
Xcode: N/A
Android Studio: Version 2.3.0.0 AI-162.4069837

Packages: (wanted => installed)
react: 16.0.0 => 16.0.0
react-native: 0.51.0 => 0.51.0

Target Platform: Android (24)
```

**Comment by webyonet** [comment]
please upgrade 2.4.3 version and try restart project

**Comment by webyonet** [comment]
has this error been resolved?

**Comment by derakhshanfar** [comment]
@webyonet thanks a lot, at the present i don't have that error.. but that error raised sometimes, i hope it fixed in latest version
