### ISSUE TITLE
There is not success in response.

### ISSUE THREAD

**Issue by MarinkoIgor** [webyonet/react-native-android-location-services-dialog-box#40]
LocationServicesDialogBox always returns error on version 2.4.3

**Comment by webyonet** [comment]
Set to enableHighAccuracy:false in options 

enableHighAccuracy: false, // true => GPS AND NETWORK PROVIDER, false => ONLY GPS PROVIDER

**Comment by MarinkoIgor** [comment]
But I need both. Now if net and gps are off it will turn on only gps.

**Comment by webyonet** [comment]
excuse me @MarinkoIgor . documents are incorrectly written. the correct document is:

enableHighAccuracy: false,
// true => GPS AND NETWORK PROVIDER
// false => GPS OR NETWORK PROVIDER

**Comment by webyonet** [comment]
I will update the documentation
