### ISSUE TITLE
How to disabled screen setting of Android

### ISSUE THREAD

**Issue by Donhv** [webyonet/react-native-android-location-services-dialog-box#41]
I want when press 'ok' in popup Location auto change and don't move to screen setting of Android.
Who can help me?

**Comment by webyonet** [comment]
Hello, this feature is not supported at the moment on this module

**Comment by Donhv** [comment]
@webyonet thanks

**Comment by Donhv** [comment]
@webyonet  can u suggest me a solution for my issue

**Comment by webyonet** [comment]
this feature can only be used with play service location.
you can look at moduls that use play service location
