### ISSUE TITLE
Illegal callback invocation from native module

### ISSUE THREAD

**Issue by sharmad1205** [webyonet/react-native-android-location-services-dialog-box#43]
Hi I am using react-native-android-location-services-dialog-box and getting the below exception

`Fatal Exception: java.lang.RuntimeException
Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
arrow_right
com.facebook.react.bridge.CallbackImpl.invoke (CallbackImpl.java:30)
com.facebook.react.bridge.PromiseImpl.reject (PromiseImpl.java:70)
com.facebook.react.bridge.PromiseImpl.reject (PromiseImpl.java:54)
com.showlocationservicesdialogbox.LocationServicesDialogBoxModule.forceCloseDialog (LocationServicesDialogBoxModule.java:45)
`

**Comment by linux-wizzard** [comment]
Same here after click **back** in android emulator
```
Illegal callback invocation from native module. This callback type only permits a single invocation from native code.
invoke
    CallbackImpl.java:30
reject
    PromiseImpl.java:70
reject
    PromiseImpl.java:54
forceCloseDialog
    LocationServicesDialogBoxModule.java:45
invoke
    Method.java
invoke
    JavaMethodWrapper.java:363
invoke
    JavaModuleWrapper.java:162
run
    NativeRunnable.java
handleCallback
    Handler.java:789
dispatchMessage
    Handler.java:98
dispatchMessage
    MessageQueueThreadHandler.java:31
loop
    Looper.java:164
run
    MessageQueueThreadImpl.java:194
run
    Thread.java:764

```

**Comment by linux-wizzard** [comment]
Ok I solved it by removing this part 
`BackHandler.addEventListener('hardwareBackPress', () => {
			LocationServicesDialogBox.forceCloseDialog();
});`
