### ISSUE TITLE
Location service not working after building the project

### ISSUE THREAD

**Issue by robado** [webyonet/react-native-android-location-services-dialog-box#48]
Getting this error 

> undefined is not an object (evaluating '_reactnative android locationservice dialogbox 2.default.check locationservice isenabled')

Thinking is this only for ejected apps or can this location checking use on every app?

**Comment by webyonet** [comment]
Rn and android version?

**Comment by webyonet** [comment]
make steps at the terminal step by step:

```
1) react-native unlink react-native-android-location-services-dialog-box
2) npm uninstall react-native-android-location-services-dialog-box
3) npm install
4) react-native link react-native-android-location-services-dialog-box
5) react-native run-android
```
