### ISSUE TITLE
Feature Request: Event Listener

### ISSUE THREAD

**Issue by gjvpaet** [webyonet/react-native-android-location-services-dialog-box#49]
Hi @webyonet first of all, thank you for this great plugin. I'm requesting if you can have a listener that listens when the user turns off their location service because as of now you have to call the function first before triggering the dialog. In my use case it should be triggered whenever the user turns off their location service. Thanks!

**Comment by havinhthai** [comment]
+ 1

**Comment by TuNguyenThanh** [comment]
+1

**Comment by havinhthai** [comment]
I'm using [React Native GPS State](https://github.com/neuberoliveira/react-native-gps-state) and it working
