### ISSUE TITLE
LocationServicesDialogBoxModule  is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener

### ISSUE THREAD

**Issue by samah2100** [webyonet/react-native-android-location-services-dialog-box#5]
I'm using RN 0.26.0 and after installing "react-native-android-location-services-dialog-box" I got this error

...\showlocationservicesdialogbox\LocationServicesDialogBoxModule.java:12: error: LocationServicesDialogBoxModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
class LocationServicesDialogBoxModule extends ReactContextBaseJavaModule implements ActivityEventListener {
^
C:\RN\1\node_modules\react-native-android-location-services-dialog-box\android\src\main\java\com\showlocationservicesdialogbox\LocationServicesDialogBoxModule.java:22: error: method does not override or implement a method from a supertype
    @Override
    ^
C:\RN\1\node_modules\react-native-android-location-services-dialog-box\android\src\main\java\com\showlocationservicesdialogbox\LocationServicesDialogBoxModule.java:77: error: method does not override or implement a method from a supertype
    @Override
    ^
3 errors
 FAILED

FAILURE: Build failed with an exception.

**Comment by webyonet** [comment]
Please Use rn 30 and older versions v1.1.7
Use 1.1.4 for other lower versions.

**Comment by webyonet** [comment]
Please see rn30 and the change of distortion of the above.

**Comment by roots-ai** [comment]
I am using the below config and still the above error.

```
"react-native": "0.44.3",
"react-native-android-location-services-dialog-box": "2.3.2",
```

**Comment by webyonet** [comment]
@roots-ai please read [releases note](https://github.com/webyonet/react-native-android-location-services-dialog-box/releases)

**Comment by itinance** [comment]
We get this compilation error since we upgraded to RN 0.50, running latest version "react-native-android-location-services-dialog-box": "2.4.3"

Any ideas?

**Comment by itinance** [comment]
Seems that with latest RN some compatibility breaks happened for android that needs to be applied here.

**Comment by itinance** [comment]
I've figured out that these compilation errors happens when "react-native-image-crop-picker" is installed in an application.
Without this library everything gets compiled.

Any ideas?

**Comment by webyonet** [comment]
this bug may be a react-native link issue.
try to manual installation please.
