### ISSUE TITLE
Build failed with an exception.

### ISSUE THREAD

**Issue by sharmad1205** [webyonet/react-native-android-location-services-dialog-box#53]
`react-native-android-lo
cation-services-dialog-box/android/src/main/java/com/showlocationservicesdial
ogbox/LocationServicesDialogBoxModule.java:13: error: LocationServicesDialogBoxModule is not abstract and does not override abstract method onActivityResult(int,int,Intent) in ActivityEventListener
class LocationServicesDialogBoxModule extends ReactContextBaseJavaModule implements ActivityEventListener {
^
/home/algofocus/ReactNativeProjects/PSP2/node_modules/react-native-android-location-services-dialog-box/android/src/main/java/com/showlocationservicesdialogbox/LocationServicesDialogBoxModule.java:25: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/algofocus/ReactNativeProjects/PSP2/node_modules/react-native-android-location-services-dialog-box/android/src/main/java/com/showlocationservicesdialogbox/LocationServicesDialogBoxModule.java:125: error: method does not override or implement a method from a supertype
    @Override
    ^
Note: /home/algofocus/ReactNativeProjects/PSP2/node_modules/react-native-android-location-services-dialog-box/android/src/main/java/com/showlocationservicesdialogbox/LocationServicesDialogBoxModule.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
3 errors`
when using with firebase crashlytics 

"react": "16.3.1",
    "react-native": "0.55.4",
    "react-native-android-location-services-dialog-box": "^2.4.4",

**Comment by webyonet** [comment]
my implementation is right. [see react native source code](https://github.com/facebook/react-native/blob/1e8f3b11027fe0a7514b4fc97d0798d3c64bc895/ReactAndroid/src/main/java/com/facebook/react/bridge/ActivityEventListener.java)

this error is  a firebase crashlytics bug.

**Comment by witalobenicio** [comment]
@webyonet how to solve that?
