### ISSUE TITLE
cannot read property 'checkLocationServicesIsEnabled' of undefined

### ISSUE THREAD

**Issue by arbabi2010** [webyonet/react-native-android-location-services-dialog-box#56]
Hi. Thank for your package
I'v used this package for react native 0.46 before and work fine . but now i want to use it in react natve 0.51 but i get this error

> cannot read property 'checkLocationServicesIsEnabled' of undefined
How can i fix it?
![image](https://user-images.githubusercontent.com/5072444/42257865-ff00a542-7f6d-11e8-99a5-321191fa47df.png)

**Comment by webyonet** [comment]
-- restart your PC or MAC (for background process)
-- uninstall your app on mobile device

folow the steps below at the terminal step by step :

```
1) react-native unlink react-native-android-location-services-dialog-box
2) npm uninstall react-native-android-location-services-dialog-box
3) npm install react-native-android-location-services-dialog-box --save
4) react-native link react-native-android-location-services-dialog-box
5) react-native run-android
```

**Comment by arbabi2010** [comment]
i have this error right now
my build is like this. is it important to be 23 ?
Kh Saeed, [04.07.18 12:41]
compileSdkVersion 27
    buildToolsVersion "27.0.3"

    defaultConfig {
        applicationId "com.kartvisit"
        minSdkVersion 16
        targetSdkVersion 27
        versionCode 1
        versionName "1.0"
        ndk {
            abiFilters "armeabi-v7a", "x86"
        }\

**Comment by webyonet** [comment]
@arbabi2010 buildToolsVersion and compileSdkVersion needs to be synchronized in every module.
the easiest way to do this is to use Android Studio.

for manual change:
`node_modules/react-native-android-location-services-dialog-box/android/build.gradle`

````gradle
android {
    compileSdkVersion 27 // here
    buildToolsVersion "27.0.3" // here

    defaultConfig {
        minSdkVersion 16
        targetSdkVersion 23
    }
}
````
