### ISSUE TITLE
Unknown named module: 'react-native-android-location-services-dialog-box'

### ISSUE THREAD

**Issue by abhitheawesomecoder** [webyonet/react-native-android-location-services-dialog-box#6]
After following ur steps of installation when i try to run my app I get error

Unknown named module: 'react-native-android-location-services-dialog-box'

I am using latest react native version

**Comment by webyonet** [comment]
Please make sure that the module is defined in MainApplication.java

`import com.showlocationservicesdialogbox.LocationServicesDialogBoxPackage;`

`return Arrays.<ReactPackage>asList(
    new MainReactPackage(),
    new LocationServicesDialogBoxPackage()
  );`

<img width="1599" alt="screen shot 2016-12-06 at 00 27 19" src="https://cloud.githubusercontent.com/assets/973302/20903222/2ff10976-bb43-11e6-9c15-6635d22c7ffa.png">

**Comment by webyonet** [comment]
Follow step by step manual installation steps
