### ISSUE TITLE
No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

### ISSUE THREAD

**Issue by Sunkari16** [webyonet/react-native-android-location-services-dialog-box#61]
creating a release build having issues.  Debug build works fine though 

.gradle/caches/transforms-1/files-1.1/appcompat-v7-26.1.0.aar/4a9597cd76950081cc172f93c5d7c4da/res/values-v26/values-v26.xml:13:5-16:13: AAPT: No resource found that matches the given name: attr 'android:keyboardNavigationCluster'.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':react-native-android-location-services-dialog-box:verifyReleaseResources'.
> com.android.ide.common.process.ProcessException: Failed to execute aapt

**Comment by webyonet** [comment]
[https://stackoverflow.com/questions/45301203/no-resource-found-that-matches-the-given-name-attr-androidkeyboardnavigationc](url)
