### ISSUE TITLE
How to use images in message?

### ISSUE THREAD

**Issue by zmnv** [webyonet/react-native-android-location-services-dialog-box#77]
Hello!

I've add icon from material design like asset in project. What I'm doing wrong?

```
message: '<img src="@drawable/ic_place_brand_24dp" />',
```

![image](https://user-images.githubusercontent.com/25253501/65428750-98c55d80-de1d-11e9-82a4-8973e60fbbcb.png)

**Comment by webyonet** [comment]
@zmnv android html also can not reach this source. try set CDN url instead

**Comment by zmnv** [comment]
@webyonet hmm, I thought about https://developer.android.com/reference/android/text/Html.ImageGetter.html

Okay. Thank you very much for your work anyway! <3
