### ISSUE TITLE
Error when building project with react-native-android-location-services-dialog-box

### ISSUE THREAD

**Issue by ranjeev75** [webyonet/react-native-android-location-services-dialog-box#8]
When I try to run a project with this module I get these errors:

`/home/user/appAndroid/node_modules/react-native-android-location-services-dialog-box/android/src/main/java/com/showlocation
servicesdialogbox/LocationServicesDialogBoxModule.java:12: error: LocationServicesDialogBoxModule is not abstract and does not ove
rride abstract method onActivityResult(int,int,Intent) in ActivityEventListener
class LocationServicesDialogBoxModule extends ReactContextBaseJavaModule implements ActivityEventListener {
^
/home/user/appAndroid/node_modules/react-native-android-location-services-dialog-box/android/src/main/java/com/showlocation
servicesdialogbox/LocationServicesDialogBoxModule.java:22: error: method does not override or implement a method from a supertype
    @Override
    ^
/home/user/appAndroid/node_modules/react-native-android-location-services-dialog-box/android/src/main/java/com/showlocation
servicesdialogbox/LocationServicesDialogBoxModule.java:77: error: method does not override or implement a method from a supertype
    @Override
    ^
3 errors
:react-native-android-location-services-dialog-box:compileReleaseJavaWithJavac FAILED

FAILURE: Build failed with an exception.`

I have react-native version 31.0

**Comment by webyonet** [comment]
Please use v1.1.4
