### ISSUE TITLE
Installing in Typescript project giving an error

### ISSUE THREAD

**Issue by sunilloharshoreline1** [webyonet/react-native-android-location-services-dialog-box#81]
I m getting an error on installing the lib. to my existing React Native Typescript project 

Could not find a declaration file for module 'react-native-android-location-services-dialog-box'. '/Users/john/Documents/ReactApps/SLCloudFrontend/vr-slcloud-frontend-v2/workspaces/mobile-app/node_modules/react-native-android-location-services-dialog-box/index.js' implicitly has an 'any' type.
Try `npm install @types/react-native-android-location-services-dialog-box` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-native-android-location-services-dialog-box';`ts(7016)

After trying **npm install @types/react-native-android-location-services-dialog-box** i m getting following error :

npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2freact-native-android-location-services-dialog-box - Not found
npm ERR! 404
npm ERR! 404  '@types/react-native-android-location-services-dialog-box@latest' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/john/.npm/_logs/2020-09-14T14_19_18_306Z-debug.log

**Comment by webyonet** [comment]
You don't need to use @type
try again with this `npm install react-native-android-location-services-dialog-box --save`
